# Autogenerated by DBIx::SearchBuilder factory (by <jesse@bestpractical.com>)
# WARNING: THIS FILE IS AUTOGENERATED. ALL CHANGES TO THIS FILE WILL BE LOST.  
# 
# !! DO NOT EDIT THIS FILE !!
#

use strict;


=head1 NAME

  RTx::ReportSources -- Collection of RTx::ReportSource objects
 
=head1 SYNOPSIS

  use RTx::ReportSources

=head1 DESCRIPTION


=head1 METHODS

=cut

package RTx::ReportSources;

use RT::SearchBuilder;
use RTx::ReportSource;

use vars qw( @ISA );
@ISA= qw(RT::SearchBuilder);


sub _Init {
    my $self = shift;
    $self->{'table'} = 'ReportSources';
    $self->{'primary_key'} = 'id';


    return ( $self->SUPER::_Init(@_) );
}


=head2 NewItem

Returns an empty new RTx::ReportSource item

=cut

sub NewItem {
    my $self = shift;
    return(RTx::ReportSource->new($self->CurrentUser));
}

        eval "require RTx::ReportSources_Overlay";
        if ($@ && $@ !~ qr{^Can't locate RTx/ReportSources_Overlay.pm}) {
            die $@;
        };

        eval "require RTx::ReportSources_Vendor";
        if ($@ && $@ !~ qr{^Can't locate RTx/ReportSources_Vendor.pm}) {
            die $@;
        };

        eval "require RTx::ReportSources_Local";
        if ($@ && $@ !~ qr{^Can't locate RTx/ReportSources_Local.pm}) {
            die $@;
        };




=head1 SEE ALSO

This class allows "overlay" methods to be placed
into the following files _Overlay is for a System overlay by the original author,
_Vendor is for 3rd-party vendor add-ons, while _Local is for site-local customizations.  

These overlay files can contain new subs or subs to replace existing subs in this module.

If you'll be working with perl 5.6.0 or greater, each of these files should begin with the line 

   no warnings qw(redefine);

so that perl does not kick and scream when you redefine a subroutine or variable in your overlay.

RTx::ReportSources_Overlay, RTx::ReportSources_Vendor, RTx::ReportSources_Local

=cut


1;
