# Autogenerated by DBIx::SearchBuilder factory (by <jesse@bestpractical.com>)
# WARNING: THIS FILE IS AUTOGENERATED. ALL CHANGES TO THIS FILE WILL BE LOST.  
# 
# !! DO NOT EDIT THIS FILE !!
#

use strict;


=head1 NAME

RTx::ReportSource


=head1 SYNOPSIS

=head1 DESCRIPTION

=head1 METHODS

=cut

package RTx::ReportSource;
use RT::Record; 
use RT::User;


use vars qw( @ISA );
@ISA= qw( RT::Record );

sub _Init {
  my $self = shift; 

  $self->Table('ReportSources');
  $self->SUPER::_Init(@_);
}





=head2 Create PARAMHASH

Create takes a hash of values and creates a row in the database:

  varchar(200) 'Name'.
  varchar(255) 'Description'.
  varchar(255) 'Driver'.
  varchar(255) 'DB'.
  varchar(255) 'Host'.
  varchar(255) 'User'.
  varchar(255) 'Password'.
  smallint(6) 'Disabled'.

=cut




sub Create {
    my $self = shift;
    my %args = ( 
                Name => '',
                Description => '',
                Driver => '',
                DB => '',
                Host => '',
                User => '',
                Password => '',
                Disabled => '0',

		  @_);
    $self->SUPER::Create(
                         Name => $args{'Name'},
                         Description => $args{'Description'},
                         Driver => $args{'Driver'},
                         DB => $args{'DB'},
                         Host => $args{'Host'},
                         User => $args{'User'},
                         Password => $args{'Password'},
                         Disabled => $args{'Disabled'},
);

}



=head2 id

Returns the current value of id. 
(In the database, id is stored as int(11).)


=cut


=head2 Name

Returns the current value of Name. 
(In the database, Name is stored as varchar(200).)



=head2 SetName VALUE


Set Name to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, Name will be stored as a varchar(200).)


=cut


=head2 Description

Returns the current value of Description. 
(In the database, Description is stored as varchar(255).)



=head2 SetDescription VALUE


Set Description to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, Description will be stored as a varchar(255).)


=cut


=head2 Driver

Returns the current value of Driver. 
(In the database, Driver is stored as varchar(255).)



=head2 SetDriver VALUE


Set Driver to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, Driver will be stored as a varchar(255).)


=cut


=head2 DB

Returns the current value of DB. 
(In the database, DB is stored as varchar(255).)



=head2 SetDB VALUE


Set DB to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, DB will be stored as a varchar(255).)


=cut


=head2 Host

Returns the current value of Host. 
(In the database, Host is stored as varchar(255).)



=head2 SetHost VALUE


Set Host to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, Host will be stored as a varchar(255).)


=cut


=head2 User

Returns the current value of User. 
(In the database, User is stored as varchar(255).)



=head2 SetUser VALUE


Set User to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, User will be stored as a varchar(255).)


=cut


=head2 UserObj

Returns the User Object which has the id returned by User


=cut

sub UserObj {
	my $self = shift;
	my $User =  RT::User->new($self->CurrentUser);
	$User->Load($self->__Value('User'));
	return($User);
}

=head2 Password

Returns the current value of Password. 
(In the database, Password is stored as varchar(255).)



=head2 SetPassword VALUE


Set Password to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, Password will be stored as a varchar(255).)


=cut


=head2 LastUpdatedBy

Returns the current value of LastUpdatedBy. 
(In the database, LastUpdatedBy is stored as int(11).)


=cut


=head2 LastUpdated

Returns the current value of LastUpdated. 
(In the database, LastUpdated is stored as datetime.)


=cut


=head2 Creator

Returns the current value of Creator. 
(In the database, Creator is stored as int(11).)


=cut


=head2 Created

Returns the current value of Created. 
(In the database, Created is stored as datetime.)


=cut


=head2 Disabled

Returns the current value of Disabled. 
(In the database, Disabled is stored as smallint(6).)



=head2 SetDisabled VALUE


Set Disabled to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, Disabled will be stored as a smallint(6).)


=cut



sub _ClassAccessible {
    {
     
        id =>
		{read => 1, type => 'int(11)', default => ''},
        Name => 
		{read => 1, write => 1, type => 'varchar(200)', default => ''},
        Description => 
		{read => 1, write => 1, type => 'varchar(255)', default => ''},
        Driver => 
		{read => 1, write => 1, type => 'varchar(255)', default => ''},
        DB => 
		{read => 1, write => 1, type => 'varchar(255)', default => ''},
        Host => 
		{read => 1, write => 1, type => 'varchar(255)', default => ''},
        User => 
		{read => 1, write => 1, type => 'varchar(255)', default => ''},
        Password => 
		{read => 1, write => 1, type => 'varchar(255)', default => ''},
        LastUpdatedBy => 
		{read => 1, auto => 1, type => 'int(11)', default => '0'},
        LastUpdated => 
		{read => 1, auto => 1, type => 'datetime', default => ''},
        Creator => 
		{read => 1, auto => 1, type => 'int(11)', default => '0'},
        Created => 
		{read => 1, auto => 1, type => 'datetime', default => ''},
        Disabled => 
		{read => 1, write => 1, type => 'smallint(6)', default => '0'},

 }
};


        eval "require RTx::ReportSource_Overlay";
        if ($@ && $@ !~ qr{^Can't locate RTx/ReportSource_Overlay.pm}) {
            die $@;
        };

        eval "require RTx::ReportSource_Vendor";
        if ($@ && $@ !~ qr{^Can't locate RTx/ReportSource_Vendor.pm}) {
            die $@;
        };

        eval "require RTx::ReportSource_Local";
        if ($@ && $@ !~ qr{^Can't locate RTx/ReportSource_Local.pm}) {
            die $@;
        };




=head1 SEE ALSO

This class allows "overlay" methods to be placed
into the following files _Overlay is for a System overlay by the original author,
_Vendor is for 3rd-party vendor add-ons, while _Local is for site-local customizations.  

These overlay files can contain new subs or subs to replace existing subs in this module.

If you'll be working with perl 5.6.0 or greater, each of these files should begin with the line 

   no warnings qw(redefine);

so that perl does not kick and scream when you redefine a subroutine or variable in your overlay.

RTx::ReportSource_Overlay, RTx::ReportSource_Vendor, RTx::ReportSource_Local

=cut


1;
